### ISSUE TITLE
Quarmtool Timers Unhandled Exception and program stalling on launch

### ISSUE THREAD

**Issue by LichLord91** [EJWellman/QuarmTool#27]
I've noticed in the lastest release a few issues.

1. When launching Quarmtool now it seems to freeze a bit before stabilizing and starting.

2. For awhile I was able to launch a timer but now i get a unhandled exception error everytime i do. 

![image](https://github.com/EJWellman/QuarmTool/assets/8435580/d0862166-9dc0-41c2-8cfc-0b426e5e4516)

```
See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.FormatException: Input string was not in a correct format.
   at System.Number.StringToNumber(String str, NumberStyles options, NumberBuffer& number, NumberFormatInfo info, Boolean parseDecimal)
   at System.Number.ParseInt32(String s, NumberStyles style, NumberFormatInfo info)
   at EQTool.Factories.TimerWindowFactory.CreateTimerWindow(TimerWindowOptions timerWindow) in B:\Hobby Stuff\QuarmTool\src\Factories\TimerWindowFactory.cs:line 47
   at EQTool.Factories.TimerWindowFactory.CreateTimerWindow(Int32 windowId) in B:\Hobby Stuff\QuarmTool\src\Factories\TimerWindowFactory.cs:line 90
   at EQTool.App.OpenTimerWindow(Object sender, EventArgs e) in B:\Hobby Stuff\QuarmTool\src\App.xaml.cs:line 810
   at System.Windows.Forms.MenuItem.OnClick(EventArgs e)
   at System.Windows.Forms.MenuItem.MenuItemData.Execute()
   at System.Windows.Forms.Command.Invoke()
   at System.Windows.Forms.Command.DispatchID(Int32 id)
   at System.Windows.Forms.NotifyIcon.WndProc(Message& msg)
   at System.Windows.Forms.NotifyIcon.NotifyIconNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)


************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9241.0 built by: NET481REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework/v4.0.30319/mscorlib.dll
----------------------------------------
QuarmTool
    Assembly Version: 1.1.0.1
    Win32 Version: 1.1.0.0
    CodeBase: file:///C:/Games/EQ/quarm%20extras/QuarmTool/QuarmTool.exe
----------------------------------------
PresentationFramework
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9241.0
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/PresentationFramework/v4.0_4.0.0.0__31bf3856ad364e35/PresentationFramework.dll
----------------------------------------
WindowsBase
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9241.0 built by: NET481REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/WindowsBase/v4.0_4.0.0.0__31bf3856ad364e35/WindowsBase.dll
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9241.0 built by: NET481REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9236.0 built by: NET481REL1LAST_B
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
PresentationCore
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9241.0 built by: NET481REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_32/PresentationCore/v4.0_4.0.0.0__31bf3856ad364e35/PresentationCore.dll
----------------------------------------
System.Xaml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9241.0 built by: NET481REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xaml/v4.0_4.0.0.0__b77a5c561934e089/System.Xaml.dll
----------------------------------------
System.Threading.Tasks.Extensions
    Assembly Version: 4.2.0.1
    Win32 Version: 1.1.0.0
    CodeBase: file:///C:/Games/EQ/quarm%20extras/QuarmTool/QuarmTool.exe
----------------------------------------
System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9037.0 built by: NET481REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9037.0 built by: NET481REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
EQToolShared
    Assembly Version: 1.0.0.0
    Win32 Version: 1.1.0.0
    CodeBase: file:///C:/Games/EQ/quarm%20extras/QuarmTool/QuarmTool.exe
----------------------------------------
System.Net.Http
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9037.0 built by: NET481REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Net.Http/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Net.Http.dll
----------------------------------------
Autofac
    Assembly Version: 7.1.0.0
    Win32 Version: 1.1.0.0
    CodeBase: file:///C:/Games/EQ/quarm%20extras/QuarmTool/QuarmTool.exe
----------------------------------------
netstandard
    Assembly Version: 2.0.0.0
    Win32 Version: 4.8.9037.0
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/netstandard/v4.0_2.0.0.0__cc7b13ffcd2ddd51/netstandard.dll
----------------------------------------
Microsoft.Bcl.AsyncInterfaces
    Assembly Version: 8.0.0.0
    Win32 Version: 1.1.0.0
    CodeBase: file:///C:/Games/EQ/quarm%20extras/QuarmTool/QuarmTool.exe
----------------------------------------
System.Threading.Tasks.Extensions
    Assembly Version: 4.2.0.1
    Win32 Version: 4.6.28619.01
    CodeBase: file:///C:/Games/EQ/quarm%20extras/QuarmTool/System.Threading.Tasks.Extensions.DLL
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9195.0 built by: NET481REL1LAST_B
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9037.0 built by: NET481REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
ZealPipes.Services
    Assembly Version: 1.0.0.0
    Win32 Version: 1.1.0.0
    CodeBase: file:///C:/Games/EQ/quarm%20extras/QuarmTool/QuarmTool.exe
----------------------------------------
ZealPipes.Common
    Assembly Version: 1.0.0.0
    Win32 Version: 1.1.0.0
    CodeBase: file:///C:/Games/EQ/quarm%20extras/QuarmTool/QuarmTool.exe
----------------------------------------
System.ValueTuple
    Assembly Version: 4.0.3.0
    Win32 Version: 1.1.0.0
    CodeBase: file:///C:/Games/EQ/quarm%20extras/QuarmTool/QuarmTool.exe
----------------------------------------
Anonymously Hosted DynamicMethods Assembly
    Assembly Version: 0.0.0.0
    Win32 Version: 4.8.9241.0 built by: NET481REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_32/mscorlib/v4.0_4.0.0.0__b77a5c561934e089/mscorlib.dll
----------------------------------------
Microsoft.Extensions.Configuration.Abstractions
    Assembly Version: 8.0.0.0
    Win32 Version: 1.1.0.0
    CodeBase: file:///C:/Games/EQ/quarm%20extras/QuarmTool/QuarmTool.exe
----------------------------------------
System.Diagnostics.DiagnosticSource
    Assembly Version: 8.0.0.0
    Win32 Version: 1.1.0.0
    CodeBase: file:///C:/Games/EQ/quarm%20extras/QuarmTool/QuarmTool.exe
----------------------------------------
System.ComponentModel.Composition
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9037.0
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.ComponentModel.Composition/v4.0_4.0.0.0__b77a5c561934e089/System.ComponentModel.Composition.dll
----------------------------------------
Newtonsoft.Json
    Assembly Version: 13.0.0.0
    Win32 Version: 1.1.0.0
    CodeBase: file:///C:/Games/EQ/quarm%20extras/QuarmTool/QuarmTool.exe
----------------------------------------
System.Runtime.Serialization
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9241.0 built by: NET481REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Runtime.Serialization/v4.0_4.0.0.0__b77a5c561934e089/System.Runtime.Serialization.dll
----------------------------------------
System.Numerics
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9037.0 built by: NET481REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Numerics/v4.0_4.0.0.0__b77a5c561934e089/System.Numerics.dll
----------------------------------------
System.Data
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9214.0 built by: NET481REL1LAST_B
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_32/System.Data/v4.0_4.0.0.0__b77a5c561934e089/System.Data.dll
----------------------------------------
System.Data.SQLite
    Assembly Version: 1.0.118.0
    Win32 Version: 1.0.118.0
    CodeBase: file:///C:/Games/EQ/quarm%20extras/QuarmTool/System.Data.SQLite.DLL
----------------------------------------
System.Transactions
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9037.0 built by: NET481REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_32/System.Transactions/v4.0_4.0.0.0__b77a5c561934e089/System.Transactions.dll
----------------------------------------
Dapper
    Assembly Version: 2.0.0.0
    Win32 Version: 1.1.0.0
    CodeBase: file:///C:/Games/EQ/quarm%20extras/QuarmTool/QuarmTool.exe
----------------------------------------
Xceed.Wpf.Toolkit
    Assembly Version: 4.5.0.0
    Win32 Version: 1.1.0.0
    CodeBase: file:///C:/Games/EQ/quarm%20extras/QuarmTool/QuarmTool.exe
----------------------------------------
Dapper.Contrib
    Assembly Version: 2.0.0.0
    Win32 Version: 1.1.0.0
    CodeBase: file:///C:/Games/EQ/quarm%20extras/QuarmTool/QuarmTool.exe
----------------------------------------
System.EnterpriseServices
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9037.0 built by: NET481REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_32/System.EnterpriseServices/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.EnterpriseServices.dll
----------------------------------------
System.Xml.Linq
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9037.0 built by: NET481REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml.Linq/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.Linq.dll
----------------------------------------
PresentationFramework.Classic
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9037.0 built by: NET481REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/PresentationFramework.classic/v4.0_4.0.0.0__31bf3856ad364e35/PresentationFramework.classic.dll
----------------------------------------
PresentationFramework-SystemXmlLinq
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9037.0
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/PresentationFramework-SystemXmlLinq/v4.0_4.0.0.0__b77a5c561934e089/PresentationFramework-SystemXmlLinq.dll
----------------------------------------
PresentationFramework-SystemXml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9037.0
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/PresentationFramework-SystemXml/v4.0_4.0.0.0__b77a5c561934e089/PresentationFramework-SystemXml.dll
----------------------------------------
UIAutomationTypes
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9241.0 built by: NET481REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/UIAutomationTypes/v4.0_4.0.0.0__31bf3856ad364e35/UIAutomationTypes.dll
----------------------------------------
UIAutomationProvider
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9241.0 built by: NET481REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/UIAutomationProvider/v4.0_4.0.0.0__31bf3856ad364e35/UIAutomationProvider.dll
----------------------------------------

************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.


```

**Comment by LichLord91** [comment]
Theres a part in here that's referencing a path that doesn't exist on my machine, is this a hardcoded path thats from your machine?

`B:\Hobby Stuff\QuarmTool\src\Factories\`


```
   at EQTool.Factories.TimerWindowFactory.CreateTimerWindow(TimerWindowOptions timerWindow) in B:\Hobby Stuff\QuarmTool\src\Factories\TimerWindowFactory.cs:line 47
   at EQTool.Factories.TimerWindowFactory.CreateTimerWindow(Int32 windowId) in B:\Hobby Stuff\QuarmTool\src\Factories\TimerWindowFactory.cs:line 90
   at EQTool.App.OpenTimerWindow(Object sender, EventArgs e) in B:\Hobby Stuff\QuarmTool\src\App.xaml.cs:line 810

```

**Comment by EJWellman** [comment]
> B:\Hobby Stuff\QuarmTool\src\Factories\

Yeah, this is from my computer. That should be safe to ignore.

Can you send me your `settings.json` file? You can send it to me via Discord if you want.
It looks like something got malformed somewhere.

**Comment by EJWellman** [comment]
Sorry, not the settings file, I need the `Quarmtool_User.db` file.

**Comment by LichLord91** [comment]
Uploaded

|[Quarmtool_User.zip](https://github.com/user-attachments/files/15595583/Quarmtool_User.zip)

**Comment by EJWellman** [comment]
I'll check it when I get home, but I think I know what's happening.

**Comment by EJWellman** [comment]
Yup, it's what I suspected.

I'm dumb, and wrote a piece badly. I'll have a release ready in just a bit.
